version: "3.9"

services:
  wordpress:
    container_name: wordpress
    image: wordpress:php8.2-fpm
    restart: always
    env_file:
      - .env
    environment:
      WORDPRESS_DB_HOST: ${CREDENTIALS_DBHOST}
      WORDPRESS_DB_USER: ${CREDENTIALS_DBUSERNAME}
      WORDPRESS_DB_PASSWORD: ${CREDENTIALS_DBPASSWORD}
      WORDPRESS_DB_NAME: ${CREDENTIALS_DBNAME}
    volumes:
      - wordpress_data:/var/www/html

  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    command: certonly --webroot --webroot-path=/var/www/html --email khomenokkg@gmail.com --agree-tos -d wp.diplomadomain.online
    volumes:
      - certbot-etc:/etc/letsencrypt
      - wordpress_data:/var/www/html

  web:
    container_name: webnginx
    image: nginx:latest
    volumes:
      - wordpress_data:/var/www/html
      - ./nginx:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
    ports:
      - "80:80"
    restart: always

volumes:
  wordpress_data:
  certbot-etc:
